#!/bin/bash
DISPLAY=:0 xprop -root -f GAMESCOPE_RESHADE_EFFECT 8u -set GAMESCOPE_RESHADE_EFFECT $1
#DISPLAY=:0 xprop -root -f GAMESCOPE_RESHADE_TECHNIQUE_IDX 8c -set GAMESCOPE_RESHADE_TECHNIQUE_IDX 0
